################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  #
  #
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: true
################################################################
# Traefik Logging
################################################################
log:
  level: DEBBUG

################################################################
# Entrypoint
################################################################
# entryPoints:
#   web:
#     address: ":80"
#   websecure:
#     address: ":443"

## Dynamic configuration
http:
  routers:
    Router-1:
      # By default, routers listen to every entry points
      rule: "Host(`thomas-chateau.net`) && Path(`/cat1`)"
      service: "catapp1"
    Router-2:
      # By default, routers listen to every entry points
      rule: "Host(`thomas-chateau.net`) && Path(`/cat2`)"
      service: "catapp2"